import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata: Metadata = {
  title: "Termos de Serviço — Klip",
  description: "Condições para usar as salas, gravação, editor e publicação do Klip.",
};

const sections = [
  ["aceite", "Aceite"], ["servico", "O serviço"], ["conta", "Conta e segurança"],
  ["conteudo", "Seu conteúdo"], ["uso", "Uso permitido"], ["plataformas", "Plataformas externas"],
  ["planos", "Planos e disponibilidade"], ["responsabilidade", "Responsabilidade"], ["encerramento", "Encerramento"],
] as const;

export default function TermsPage() {
  return <main className={styles.page}>
    <header className={styles.header}><Link className={styles.brand} href="/"><i />Klip</Link><nav className={styles.nav}><Link href="/privacidade">Política de Privacidade</Link><Link className={styles.back} href="/">Voltar ao Klip</Link></nav></header>
    <section className={styles.hero}><span className={styles.eyebrow}>Regras claras</span><h1>Termos de Serviço.</h1><p>Estas condições regulam o uso das salas, gravação, editor, Klip Radar, estúdio offline e recursos de publicação do Klip.</p><span className={styles.updated}>Última atualização: 27 de agosto de 2026</span></section>
    <div className={styles.layout}>
      <aside className={styles.toc}><b>Nesta página</b>{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside>
      <article className={styles.content}>
        <div className={styles.summary}><div><b>Você controla a gravação</b><span>Obtenha autorização dos participantes antes de gravar.</span></div><div><b>Seu conteúdo continua seu</b><span>Você concede apenas a licença necessária para operar o serviço.</span></div><div><b>Publicação é opcional</b><span>Nada é enviado às redes sem uma ação sua.</span></div></div>
        <section className={`${styles.section} ${styles.notice}`} id="aceite"><h2>1. Aceite dos termos</h2><p>Ao acessar ou usar o Klip, você concorda com estes Termos e com a <Link href="/privacidade">Política de Privacidade</Link>. Se estiver usando o serviço em nome de uma empresa, declara possuir poderes para vinculá-la. Caso não concorde, não utilize o serviço.</p><p>Você deve ter capacidade legal para contratar. Menores de idade somente podem usar o Klip com autorização e supervisão de responsável legal.</p></section>
        <section className={styles.section} id="servico"><h2>2. O que o Klip oferece</h2><p>O Klip reúne videochamadas, gravação local, compartilhamento de tela, chat, composição de câmera, fundos virtuais, edição, criação de GIFs, análise local de possíveis cortes e publicação opcional em plataformas externas.</p><p>Recursos podem variar conforme navegador, sistema operacional, equipamento, codec, conexão e permissões. Funcionalidades experimentais ou inteligentes geram sugestões e exigem revisão humana; elas não garantem resultado, audiência, receita ou precisão perfeita.</p></section>
        <section className={styles.section} id="conta"><h2>3. Conta, salas e segurança</h2><ul><li>Forneça informações corretas e mantenha suas credenciais protegidas.</li><li>Você é responsável pelas ações realizadas em sua conta e pelos links, códigos e senhas de sala que compartilhar.</li><li>Avise os convidados quando uma sessão estiver sendo gravada e obtenha os consentimentos exigidos.</li><li>Não tente acessar contas, salas ou dados de terceiros sem autorização.</li></ul><p>Podemos limitar sessões ou exigir nova autenticação quando houver indício de abuso, risco de segurança ou violação destes Termos.</p></section>
        <section className={styles.section} id="conteudo"><h2>4. Conteúdo e direitos autorais</h2><p>Você mantém a titularidade do conteúdo que grava, importa ou cria. Concede ao Klip uma licença limitada, mundial e pelo tempo necessário para hospedar, processar, converter, transmitir e publicar esse conteúdo exclusivamente para fornecer as funções solicitadas.</p><p>Você declara possuir direitos e autorizações sobre vozes, imagens, músicas, marcas e demais materiais utilizados. É proibido enviar conteúdo que viole privacidade, direitos autorais, imagem, honra, segredo, contrato ou qualquer lei. Bibliotecas identificadas como “Klip Original” seguem a licença exibida no próprio editor; arquivos externos permanecem sob responsabilidade do usuário.</p></section>
        <section className={styles.section} id="uso"><h2>5. Uso permitido</h2><p>Você não pode usar o Klip para:</p><ul><li>assediar, ameaçar, fraudar, personificar ou explorar terceiros;</li><li>gravar pessoas sem base legal ou consentimento quando necessário;</li><li>distribuir malware, spam, material ilícito ou conteúdo que viole direitos;</li><li>interferir na infraestrutura, contornar limites, explorar vulnerabilidades ou realizar engenharia reversa indevida;</li><li>usar automação abusiva, revender acesso sem autorização ou sobrecarregar o serviço;</li><li>criar conteúdo enganoso que possa causar dano sem a devida contextualização.</li></ul></section>
        <section className={styles.section} id="plataformas"><h2>6. Serviços e plataformas externas</h2><p>Login, armazenamento, conectividade e publicação podem depender de Supabase, Vercel, infraestrutura WebRTC, Google/YouTube, TikTok e Meta/Instagram. O uso desses serviços também está sujeito aos respectivos termos, políticas, limites de API e decisões de moderação.</p><p>O Klip não controla indisponibilidades, bloqueios, mudanças de API, compressão, alcance, remoção ou monetização realizados por terceiros. Você pode desconectar suas contas sociais pelo perfil; a revogação pode exigir ação adicional na plataforma correspondente.</p></section>
        <section className={styles.section} id="planos"><h2>7. Planos, pagamentos e disponibilidade</h2><p>Recursos gratuitos, promocionais ou em teste podem ser alterados ou encerrados. Antes da cobrança de qualquer plano, serão informados preço, periodicidade, tributos aplicáveis, renovação e forma de cancelamento. Ofertas exibidas como futuras ou experimentais não constituem obrigação de lançamento.</p><p>Buscamos manter o serviço disponível, mas não garantimos operação ininterrupta. Podemos realizar manutenção, corrigir falhas, alterar a interface e atualizar requisitos técnicos.</p></section>
        <section className={styles.section} id="responsabilidade"><h2>8. Garantias e responsabilidade</h2><p>O serviço é oferecido no estado em que se encontra e conforme disponibilidade, respeitados os direitos obrigatórios do consumidor. Faça cópias dos arquivos importantes e confira o vídeo antes de publicar. O Klip não substitui aconselhamento jurídico sobre consentimento, licenciamento ou publicidade.</p><p>Na extensão permitida pela lei, não respondemos por perda decorrente de falha do dispositivo, conexão, navegador, plataforma externa, exclusão acidental, uso não autorizado ou conteúdo criado por usuários. Nada nestes Termos exclui responsabilidade que não possa ser afastada pela legislação aplicável.</p></section>
        <section className={styles.section} id="encerramento"><h2>9. Suspensão, encerramento e lei aplicável</h2><p>Você pode deixar de usar o serviço, desconectar integrações e solicitar a exclusão da conta. Podemos suspender ou encerrar acesso por violação destes Termos, risco à segurança, exigência legal ou descontinuação, buscando aviso prévio quando razoável.</p><p>Estes Termos são regidos pelas leis da República Federativa do Brasil. Fica preservado o foro legalmente competente, inclusive o domicílio do consumidor quando aplicável. Dúvidas ou notificações devem ser enviadas pelo canal de suporte disponibilizado no aplicativo.</p></section>
      </article>
    </div>
    <footer className={styles.footer}><span>© 2026 Klip. Crie, edite e publique.</span><span><Link href="/privacidade">Política de Privacidade</Link> · <Link href="/">Aplicativo</Link></span></footer>
  </main>;
}
