import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("keeps the Klip editor interaction model in the production source", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  assert.match(page, /function ClipEditorV2/);
  assert.match(page, /function beginTimelineItemDrag/);
  assert.match(page, /function moveTimelineItemDrag/);
  assert.match(page, /function beginTimelineFadeDrag/);
  assert.match(page, /function beginPlayheadDrag/);
  assert.match(page, /function copySelected/);
  assert.match(page, /function pasteSelected/);
  assert.match(page, /function openContextMenu/);
  assert.match(page, /function updateSnapGuide/);
  assert.match(page, /function addSceneVideo/);
  assert.match(page, /function addSceneMedia/);
  assert.match(page, /function splitSelectedAtPlayhead/);
  assert.match(page, /function openVideoContextMenu/);
  assert.match(page, /Vídeo na sequência: arraste para mover/);
  assert.match(page, /VÍDEO PRINCIPAL/);
  assert.match(page, /target: "main" \| "scene"/);
  assert.match(page, /role: "scene"/);
  assert.match(page, /editor-workspace-empty/);
  assert.match(page, /scaleX: 1, scaleY: 1/);
  assert.match(page, /beginVideoFrameResize\(event, "corner"\)/);
  assert.match(page, /function turnPhotoIntoClip/);
  assert.match(page, /function togglePreviewPlayback/);
  assert.match(page, /function playTimelineAt/);
  assert.match(page, /const baseLoopOffset/);
  assert.match(page, /onEnded=\{\(event\) => void playTimelineAt/);
  assert.match(page, /const hasFriendVideo/);
  assert.match(page, /A recording in a solo room is a proper one-person composition/);
  assert.match(page, /Nunca abra uma segunda chamada ao alterar fundo\/overlay/);
  assert.match(page, /const stream = processedLocal\.current \|\| local\.current/);
  assert.match(page, /let loadedOverlaySource = cameraOverlayRef\.current/);
  assert.match(page, /if \(background\) image\.src = background/);
  assert.match(page, /Nunca faça composição em 4K implícita/);
  assert.match(page, /Usando IA Premium compatível com este navegador/);
  assert.match(page, /const usePremiumMatting = mattingQuality === "premium" \|\| isMacOS/);
  assert.match(page, /"Identity:0", "Identity_1:0", "Identity_2:0"/);
  assert.match(page, /frameRate: \{ ideal: 30, max: 30 \}/);
  assert.match(page, /firstMaskTimer = window\.setTimeout/);
  assert.match(page, /Carregando e preparando o GIF/);
  assert.match(page, /inferenceDuration > 95 \? 384/);
  assert.match(page, /Vídeo e enquadramento/);
  assert.match(page, /Arraste diretamente na prévia ou faça o ajuste preciso aqui/);
  assert.match(page, /Horizontal · \{Math\.round\(selectedIllustration\.x\)\}%/);
  assert.match(page, /event\.key === "Delete"/);
  assert.match(page, /event\.code === "Space"/);
});

test("ships direct-manipulation styling for desktop and mobile timelines", async () => {
  const css = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(css, /\.timeline-item-clip/);
  assert.match(css, /\.timeline-clip-handle/);
  assert.match(css, /\.timeline-transition/);
  assert.match(css, /\.timeline-play-toggle/);
  assert.match(css, /\.clip-fade-handle/);
  assert.match(css, /\.timeline-context-menu/);
  assert.match(css, /\.timeline-snap-guide/);
  assert.match(css, /\.tool-disclosure/);
  assert.match(css, /\.editor-workspace-empty/);
  assert.match(css, /\.editor-empty-upload/);
  assert.match(css, /\.media-destinations/);
  assert.match(css, /\.editor-replace-upload/);
  assert.match(css, /\.video-frame-resize\.edge/);
  assert.match(css, /\.scene-track-heading/);
  assert.match(css, /\.primary-video-clip/);
  assert.match(css, /\.timeline-more/);
  assert.match(css, /\.video-properties-grid/);
  assert.match(css, /\.position-grid/);
  assert.match(css, /\.settings-panel::-webkit-scrollbar/);
  assert.match(css, /\.virtual-effect-loading/);
  assert.match(css, /@media \(max-width: 760px\)/);
});
