import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("keeps the KLIPAPP editor interaction model in the production source", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  assert.match(page, /function ClipEditorV2/);
  assert.match(page, /function beginTimelineItemDrag/);
  assert.match(page, /function beginPrimaryTimelineMove/);
  assert.match(page, /function movePrimaryTimelineMove/);
  assert.match(page, /primaryTimelineStart/);
  assert.match(page, /O trecho cortado foi preservado/);
  assert.match(page, /function moveTimelineItemDrag/);
  assert.match(page, /function beginTimelineFadeDrag/);
  assert.match(page, /function beginPlayheadDrag/);
  assert.match(page, /function copySelected/);
  assert.match(page, /function pasteSelected/);
  assert.match(page, /function openContextMenu/);
  assert.match(page, /function updateSnapGuide/);
  assert.match(page, /function addSceneVideo/);
  assert.match(page, /function addSceneMedia/);
  assert.match(page, /function splitSelectedAtPlayhead/);
  assert.match(page, /function openVideoContextMenu/);
  assert.match(page, /Vídeo na sequência: arraste para mover/);
  assert.match(page, /VÍDEO PRINCIPAL/);
  assert.match(page, /target: "main" \| "scene"/);
  assert.match(page, /role: "scene"/);
  assert.match(page, /editor-workspace-empty/);
  assert.match(page, /scaleX: 1, scaleY: 1/);
  assert.match(page, /beginVideoFrameResize\(event, "corner"\)/);
  assert.match(page, /function turnPhotoIntoClip/);
  assert.match(page, /function togglePreviewPlayback/);
  assert.match(page, /function playTimelineAt/);
  assert.match(page, /const baseLoopOffset/);
  assert.match(page, /onEnded=\{\(\) => \{ if \(!exportInProgress\.current\) void playTimelineAt/);
  assert.match(page, /const hasFriendVideo/);
  assert.match(page, /A recording in a solo room is a proper one-person composition/);
  assert.match(page, /type VerticalCameraMode = "auto" \| "solo-mine" \| "solo-friend"/);
  assert.match(page, /TikTok solo ativo: somente a sua câmera será gravada em 9:16/);
  assert.match(page, /Câmera \/ placa de captura/);
  assert.match(page, /Placa de captura —/);
  assert.match(page, /Nunca abra uma segunda chamada ao alterar fundo\/overlay/);
  assert.match(page, /const stream = processedLocal\.current \|\| local\.current/);
  assert.match(page, /let loadedOverlaySource = cameraOverlayRef\.current/);
  assert.match(page, /if \(background\) image\.src = background/);
  assert.match(page, /Nunca faça composição em 4K implícita/);
  assert.match(page, /Usando IA Premium compatível com este navegador/);
  assert.match(page, /const usePremiumMatting = mattingQuality === "premium" && !isMacOS/);
  assert.match(page, /"Identity:0", "Identity_1:0", "Identity_2:0"/);
  assert.match(page, /frameRate: \{ ideal: 30, max: 30 \}/);
  assert.match(page, /shareScreenDialogOpen/);
  assert.match(page, /Tela com áudio/);
  assert.match(page, /Somente imagem/);
  assert.match(page, /systemAudio: includeAudio \? "include" : "exclude"/);
  assert.match(page, /setRemoteScreenAudioActive\(shared\.getAudioTracks\(\)\.length > 0\)/);
  assert.match(page, /firstMaskTimer = window\.setTimeout/);
  assert.match(page, /const macPort: SegmentPort/);
  assert.match(page, /Recorte compatível com macOS pronto/);
  assert.match(page, /selfie_multiclass_256x256\.tflite/);
  assert.match(page, /worker\.postMessage\(\{ type: "segment", frame: inferenceCanvas/);
  assert.match(page, /Carregando e preparando o GIF/);
  assert.match(page, /inferenceDuration > 95 \? 384/);
  assert.match(page, /Vídeo e enquadramento/);
  assert.match(page, /Arraste diretamente na prévia ou faça o ajuste preciso aqui/);
  assert.match(page, /Horizontal · \{Math\.round\(selectedIllustration\.x\)\}%/);
  assert.match(page, /event\.key === "Delete"/);
  assert.match(page, /event\.code === "Space"/);
  assert.match(page, /function buildAudioWaveform/);
  assert.match(page, /timelineWaveform/);
  assert.match(page, /audio-clip-waveform/);
  assert.match(page, /function splitActiveRadarCutAtPlayhead/);
  assert.match(page, /function beginRadarCutTrim/);
  assert.match(page, /function beginRadarCutMove/);
  assert.match(page, /timelineStart: timelineCursor/);
  assert.match(page, /A linha branca permaneceu onde estava/);
  assert.match(page, /montageAudioClips\.map/);
  assert.match(page, /\[5, 10, 15, 20, 30\]/);
  assert.match(page, /function dropTransitionOnRadarClip/);
  assert.match(page, /application\/x-klip-transition", "flash"/);
  assert.match(page, /application\/x-klip-transition", "dissolve"/);
  assert.match(page, /application\/x-klip-transition", "wipe"/);
  assert.match(page, /activeTransitionKind === "wipe"/);
  assert.match(page, /timeline-split-toggle/);
});

test("ships direct-manipulation styling for desktop and mobile timelines", async () => {
  const css = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(css, /\.timeline-item-clip/);
  assert.match(css, /\.timeline-clip-handle/);
  assert.match(css, /\.timeline-transition/);
  assert.match(css, /\.timeline-play-toggle/);
  assert.match(css, /\.clip-fade-handle/);
  assert.match(css, /\.timeline-context-menu/);
  assert.match(css, /\.timeline-snap-guide/);
  assert.match(css, /\.tool-disclosure/);
  assert.match(css, /\.editor-workspace-empty/);
  assert.match(css, /\.editor-empty-upload/);
  assert.match(css, /\.media-destinations/);
  assert.match(css, /\.editor-replace-upload/);
  assert.match(css, /\.video-frame-resize\.edge/);
  assert.match(css, /\.scene-track-heading/);
  assert.match(css, /\.primary-video-clip/);
  assert.match(css, /\.screen-share-dialog/);
  assert.match(css, /\.timeline-more/);
  assert.match(css, /\.video-properties-grid/);
  assert.match(css, /\.position-grid/);
  assert.match(css, /\.settings-panel::-webkit-scrollbar/);
  assert.match(css, /\.virtual-effect-loading/);
  assert.match(css, /\.audio-clip-waveform/);
  assert.match(css, /\.radar-trim-handle/);
  assert.match(css, /\.radar-clip-fade/);
  assert.match(css, /\.montage-audio-clip/);
  assert.match(css, /\.segmented-waveform/);
  assert.match(css, /\.montage-audio-waveform::after/);
  assert.match(css, /\.transition-shelf button:hover/);
  assert.match(css, /@media \(max-width: 760px\)/);
});

test("ships the image-to-GIF motion studio and camera background handoff", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const studio = await readFile(new URL("app/gif-studio.tsx", root), "utf8");
  const css = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(page, /<WandSparkles aria-hidden="true" \/> Motion/);
  assert.match(page, /<GifStudio/);
  assert.match(studio, /function paintMotionFrame/);
  assert.match(studio, /function lzwPixels/);
  assert.match(studio, /"GIF89a"/);
  assert.match(studio, /Usar como fundo/);
  assert.match(studio, /Arraste para reorganizar/);
  assert.match(css, /\.motion-studio/);
  assert.match(css, /\.motion-frame-list/);
  assert.match(css, /\.motion-exporting/);
});

test("ships the local KLIPAPP Radar review flow without replacing the source", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const radar = await readFile(new URL("app/klip-radar.ts", root), "utf8");
  const css = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(page, /autoAnalyze\?: boolean/);
  assert.match(page, /function runRadarAnalysis/);
  assert.match(page, /function applyRadarSuggestions/);
  assert.match(page, /function previewRadarSuggestion/);
  assert.match(page, /const montageRanges/);
  assert.match(page, /const montageTimelineClips/);
  assert.match(page, /const editorTimelineDuration/);
  assert.match(page, /Montagem livre/);
  assert.match(page, /\? "ÁUDIOS" : "ÁUDIO"/);
  assert.match(page, /vídeo e áudio independentes/);
  assert.match(page, /Salvar este clipe sem remover os demais/);
  assert.match(page, /exportReel\(false, \[item\]/);
  assert.match(page, /Os demais clipes continuam na montagem/);
  assert.match(page, /const exportInProgress = useRef\(false\)/);
  assert.match(page, /if \(exportInProgress\.current\) return/);
  assert.match(page, /finishExportWithError/);
  assert.match(page, /document\.body\.appendChild\(link\)/);
  assert.match(page, /function advanceMontageRange/);
  assert.match(page, /fades automáticos/);
  assert.match(page, /Exportar \$\{approvedCuts\.length\} clipes/);
  assert.match(page, /setEditorOpen\(true\)/);
  assert.match(page, /KLIP RADAR/);
  assert.match(page, /Nada altera o arquivo original/);
  assert.match(radar, /export async function analyzeClipForRadar/);
  assert.match(radar, /Mapeando ritmo e intensidade/);
  assert.match(radar, /decodeAudioData/);
  assert.match(radar, /sugestões estimadas para conferir/);
  assert.match(css, /\.radar-panel/);
  assert.match(css, /\.radar-cut/);
  assert.match(css, /\.radar-trigger/);
  assert.match(css, /Studio readability pass/);
  assert.match(css, /Export\/Radar usability/);
  assert.match(css, /height: min\(88dvh, 860px\)/);
});

test("KLIPAPP Radar finds separate speech blocks and keeps them inside the source", async () => {
  const { buildSuggestions } = await import("../app/klip-radar.ts");
  const levels = Array.from({ length: 900 }, () => 0.002);
  for (let index = 50; index < 300; index += 1) levels[index] = index % 37 < 3 ? 0.004 : 0.08;
  for (let index = 380; index < 680; index += 1) levels[index] = index % 43 < 4 ? 0.004 : 0.065;
  const suggestions = buildSuggestions(levels, 0.1, 90, "reels", 5);
  assert.ok(suggestions.length >= 2);
  assert.ok(suggestions.every((item) => item.start >= 0 && item.end <= 90));
  assert.ok(suggestions.every((item) => item.end > item.start && item.selected));
  assert.ok(suggestions.some((item) => item.start < 10));
  assert.ok(suggestions.some((item) => item.start >= 25));
});
