import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata: Metadata = {
  title: "Política de Privacidade — Klip",
  description: "Saiba como o Klip trata dados pessoais, gravações, contas conectadas e preferências.",
};

const sections = [
  ["visao-geral", "Visão geral"], ["dados", "Dados tratados"], ["uso", "Como usamos"],
  ["midia", "Vídeo, áudio e IA"], ["compartilhamento", "Compartilhamento"], ["armazenamento", "Armazenamento"],
  ["direitos", "Seus direitos"], ["seguranca", "Segurança"], ["alteracoes", "Alterações e contato"],
] as const;

export default function PrivacyPage() {
  return <main className={styles.page}>
    <header className={styles.header}><Link className={styles.brand} href="/"><i />Klip</Link><nav className={styles.nav}><Link href="/termos">Termos de Serviço</Link><Link className={styles.back} href="/">Voltar ao Klip</Link></nav></header>
    <section className={styles.hero}><span className={styles.eyebrow}>Privacidade no Klip</span><h1>Seus dados, sem mistério.</h1><p>Esta política explica quais informações o Klip utiliza, quando uma mídia permanece no seu dispositivo e quando ela precisa ser enviada para viabilizar recursos online.</p><span className={styles.updated}>Última atualização: 27 de agosto de 2026</span></section>
    <div className={styles.layout}>
      <aside className={styles.toc}><b>Nesta página</b>{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside>
      <article className={styles.content}>
        <div className={styles.summary}><div><b>Gravação local</b><span>Por padrão, a gravação e a edição acontecem no navegador.</span></div><div><b>Controle do usuário</b><span>Você escolhe quando conectar contas ou enviar uma mídia.</span></div><div><b>WebRTC</b><span>Chamadas usam conexão em tempo real entre participantes.</span></div></div>
        <section className={`${styles.section} ${styles.notice}`} id="visao-geral"><h2>1. Visão geral</h2><p>O <strong>Klip</strong> é uma plataforma web para videochamadas, gravação, composição de câmera, edição de vídeos e publicação em redes sociais. Para fins da Lei Geral de Proteção de Dados Pessoais — LGPD, o Klip atua como controlador dos dados de conta e uso descritos nesta política. Em conteúdos que você decide publicar, as plataformas de destino também tratam dados segundo suas próprias regras.</p><p>Ao usar o serviço, você declara ter lido esta política. Recursos opcionais que exigem permissões — câmera, microfone, tela, arquivos ou contas sociais — somente são ativados após uma ação sua e autorização do navegador ou da plataforma correspondente.</p></section>
        <section className={styles.section} id="dados"><h2>2. Dados que podemos tratar</h2><ul><li><strong>Conta e perfil:</strong> nome, e-mail, foto, identificador de usuário e dados básicos fornecidos pelo login.</li><li><strong>Sessão:</strong> código da sala, nome exibido, estado da conexão, mensagens do chat e informações técnicas necessárias à chamada.</li><li><strong>Dispositivo e diagnóstico:</strong> navegador, permissões, resolução, FPS, bitrate, latência, jitter, perda de pacotes e registros de erro.</li><li><strong>Mídia:</strong> câmera, microfone, compartilhamento de tela, vídeos, imagens, GIFs, áudios, textos e projetos selecionados por você.</li><li><strong>Contas sociais:</strong> identificador, nome do canal/perfil, permissões OAuth, tokens de acesso e histórico de publicações quando você conectar YouTube, TikTok ou Instagram.</li><li><strong>Preferências locais:</strong> tema, rascunho do editor e informações de sessão salvas no armazenamento do navegador.</li></ul></section>
        <section className={styles.section} id="uso"><h2>3. Para que usamos os dados</h2><p>Usamos os dados para autenticar sua conta, conectar participantes, manter a chamada, gravar e editar conteúdo, salvar preferências, publicar nas plataformas escolhidas, prestar suporte, prevenir fraude, diagnosticar falhas e melhorar estabilidade e desempenho.</p><p>As bases legais podem incluir execução do serviço solicitado, cumprimento de obrigação legal, exercício regular de direitos, legítimo interesse com avaliação de impacto e consentimento quando exigido. Você pode revogar permissões opcionais pelo navegador, dispositivo ou plataforma conectada.</p></section>
        <section className={styles.section} id="midia"><h2>4. Vídeo, áudio e recursos inteligentes</h2><h3>Processamento local</h3><p>A gravação, o editor, o Klip Radar, os efeitos e a composição de fundo foram projetados para operar no navegador sempre que possível. Nesses casos, a mídia não é enviada ao Klip apenas para realizar o processamento.</p><h3>Chamadas</h3><p>Áudio, vídeo, tela e chat trafegam por WebRTC entre os participantes. Serviços de sinalização e servidores STUN/TURN podem processar metadados de conexão e, quando uma conexão direta não for possível, retransmitir o fluxo criptografado em trânsito.</p><h3>Upload e publicação</h3><p>Quando você solicita upload, armazenamento em nuvem ou publicação, o arquivo é enviado aos serviços necessários. O Klip não publica conteúdo sem uma ação explícita sua. Você é responsável por obter autorização das pessoas gravadas e por não enviar material ilícito ou sem os direitos necessários.</p></section>
        <section className={styles.section} id="compartilhamento"><h2>5. Com quem os dados podem ser compartilhados</h2><ul><li><strong>Supabase:</strong> autenticação, banco de dados e armazenamento de mídias quando esses recursos são utilizados.</li><li><strong>Vercel:</strong> hospedagem, entrega do aplicativo e registros técnicos.</li><li><strong>Google/YouTube, TikTok e Meta/Instagram:</strong> autenticação OAuth e publicação solicitada por você.</li><li><strong>Infraestrutura WebRTC:</strong> sinalização e conectividade de chamadas, incluindo serviços STUN.</li><li><strong>Autoridades:</strong> quando necessário para cumprir obrigação legal ou proteger direitos.</li></ul><p>Não vendemos seus dados pessoais. Alguns fornecedores podem processar dados fora do Brasil, com as salvaguardas aplicáveis e conforme seus próprios termos.</p></section>
        <section className={styles.section} id="armazenamento"><h2>6. Armazenamento e retenção</h2><p>Preferências e rascunhos locais permanecem no seu navegador até você apagá-los, limpar os dados do site ou desinstalar o navegador. Dados de conta e publicações permanecem enquanto a conta estiver ativa ou pelo período necessário às finalidades informadas. Arquivos enviados podem permanecer até serem excluídos, expirarem ou deixarem de ser necessários.</p><p>Tokens de contas sociais são mantidos para executar as ações autorizadas e podem ser revogados ao desconectar a conta. Certos registros podem ser preservados para segurança, prevenção de abuso, cumprimento legal ou exercício de direitos.</p></section>
        <section className={styles.section} id="direitos"><h2>7. Seus direitos</h2><p>Nos termos da LGPD, você pode solicitar confirmação e acesso ao tratamento, correção, informação sobre compartilhamento, anonimização, bloqueio, eliminação, portabilidade quando aplicável, revisão de decisões automatizadas e revogação do consentimento. A exclusão pode ser limitada por obrigações legais ou hipóteses de conservação previstas em lei.</p><p>Solicitações devem ser feitas pelo canal de suporte disponibilizado no aplicativo. Podemos pedir informações para confirmar sua identidade. Consulte também as orientações oficiais da <a href="https://www.gov.br/anpd/pt-br/assuntos/titular-de-dados-1/direito-dos-titulares" target="_blank" rel="noreferrer">Autoridade Nacional de Proteção de Dados</a>.</p></section>
        <section className={styles.section} id="seguranca"><h2>8. Segurança</h2><p>Adotamos medidas técnicas e organizacionais proporcionais ao risco, como conexões HTTPS, autenticação, escopo limitado de permissões e controles de acesso. Nenhum sistema é absolutamente invulnerável; por isso, proteja suas credenciais, não compartilhe a senha da sala publicamente e desconecte contas que não utiliza.</p></section>
        <section className={styles.section} id="alteracoes"><h2>9. Alterações, idade e contato</h2><p>O serviço não é direcionado a crianças. Menores de idade somente devem utilizá-lo com autorização e supervisão de seu responsável legal, respeitando a legislação aplicável.</p><p>Podemos atualizar esta política para refletir mudanças no produto ou na lei. A data no topo indica a versão vigente. Para dúvidas, solicitações de titular ou relatos de privacidade, utilize o canal de suporte exibido no aplicativo ou no perfil da sua conta.</p></section>
      </article>
    </div>
    <footer className={styles.footer}><span>© 2026 Klip. Crie, edite e publique.</span><span><Link href="/termos">Termos de Serviço</Link> · <Link href="/">Aplicativo</Link></span></footer>
  </main>;
}
